### ISSUE TITLE
Additon to Do and Dont list

### ISSUE THREAD

**Issue by TaylorEllington** [Hacking-and-Coffee/defcon-for-n00bs#2]
I would recommend adding:

Do: carry cash
Don't: pay by, carry, or demonstrate possession of credit cards or "pay by phone" wallets.

**Comment by hon1nbo** [comment]
Can add these without much issue. DC has users who use cards in vendor area recommendations, and if they have taken precautions this can be done without too much issue (I.e. they watch their reports, setup spending limits, use a prepaid or proxy card, etc). I will work out some lines to add in good detail, but I think I should probably make an actual section on it. If you have suggestions for wording in line, or want to make a file on things like prepaid / proxy cards , feel free to submit a pull or post here.

Cheers,
-H

**Comment by hon1nbo** [comment]
Have had some additions to some cash/atm recommendations. I am currently working on other notes, but right now I think there is enough basics. Will consider further details to merge in, but it is not my focus at the moment.

**Comment by hon1nbo** [comment]
Seems like this is basically covered right now; I don't think this needs to stay open unless there are other specific recommendations in mind.

Cheers,
~H
